# Workflow to build and publish the libzim ASM and WASM arttefacts together with the JavaScript wrapper.
# If this workflow is triggered by the creation of a draft release, then the artefacts are uploaded to the release assets.
# If it is triggered by a push or pull request to master, or manually, then the artefacts are archived under the corresponding Action.

name: Build and publish release artefacts (Docker)

on:
  push:
    branches: [ master ]
    tags:
    - 'v*' # Push events matching v*, i.e. v1.0, v20.15.10
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch:
    inputs:
      version:
        description: |
          If you wish to create a draft release, set the tag version, like v9.9.9 (must not be an exisitng tag).
          If left blank or incorrect format, archives will be archived instead of being uploaded to Releases.
        required: false
        default: ''

# Define top-level environment vars we can refer to below
env:
  VERSION: ${{ github.ref_name }}
  DISPATCH_VERSION: ${{ github.event.inputs.version }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
jobs:
  build:
    name: Build and publish W/ASM artefacts 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # Customizes the Emscripten docker container via the Dockerfile in this repo
    # - name: Build the Docker image
    #   run: docker build -t "docker-emscripten-libzim:v3" ./docker
    # Creates the ASM and WASM artefacts, and the JS wrappers, using the Makefile in this repo
    # - name: Compile the libzim WASM artefacts
    #   run: docker run --rm -v $(pwd):/src -u $(id -u):$(id -g) docker-emscripten-libzim:v3 make
    - name: List files in top-level directory
      run: ls -l
    # If we are not creating a release, archive the artefacts under this Action run
    - name: Archive build artefacts
      if:  github.event_name == 'pull_request' || github.event_name == 'push' && ! startsWith(github.ref_name, 'v') || ! startsWith(github.event.inputs.version, 'v')
      uses: actions/upload-artifact@v3
      with:
        name: libzim-wasm-artefacts
        path: |
          libzim-wasm.*
          libzim-asm.*
    # Otherwise, zip the artefacts into respective packages (asm and wasm), create and upload releases
    - name: Zip the artefacts and create draft release
      id: zip-release
      if: github.event_name == 'push' && startsWith(github.ref_name, 'v') || startsWith(github.event.inputs.version, 'v')
      run: |
        if [[ ! $VERSION =~ ^v?[0-9.]+ ]]; then
          VERSION=$DISPATCH_VERSION
        fi
        echo "Zipping the release archives..."
        zip libzim-wasm_$VERSION.zip libzim-wasm.*
        zip libzim-asm_$VERSION.zip libzim-asm.*
        echo "Creating the draft release..."
        REST_RESPONSE=$(
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
              https://api.github.com/repos/openzim/javascript-libzim/releases \
            -d "{\"tag_name\":\"$VERSION\",\"target_commitish\":\"master\",\"name\":\"Release $VERSION\",\"body\":\"\",\"draft\":true,\"prerelease\":false,\"generate_release_notes\":true}"
        )
        echo $REST_RESPONSE
        UPLOAD_URL=$(echo $REST_RESPONSE | jq -r '.upload_url')
        UPLOAD_URL=$(sed -E 's/\{.+\}$//' <<<"$UPLOAD_URL")
        if [ -z $UPLOAD_URL ]; then
          echo -e "\n***ERROR! We could not create the draft release!***"
          exit 2
        else
          echo "Draft release created, files will be uploaded to: $UPLOAD_URL"
        fi
        # echo "UPLOAD_URL=$REST_RESPONSE" >> $GITHUB_OUTPUT # Use this if you need to access the URL in a later step with steps.zip-release.outputs.UPLOAD_URL
        # Upload archives to the draft release
        for FILE in "libzim-wasm_$VERSION.zip" "libzim-asm_$VERSION.zip"
        do
          echo -e "\nUploading $FILE..."
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/zip"
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            $UPLOAD_URL?name=$FILE
        done
    # Publish the artefacts to the GitHub draft release
    # - name: Publish zipped WASM artefacts to GitHub release
    #   if: startsWith(env.VERSION, 'v')
    #   uses: actions/upload-release-asset@v1
    #   with:
    #     upload_url: ${{ steps.zip-release.outputs.UPLOAD_URL }}
    #     asset_path: ./libzim-wasm_${{ env.VERSION }}.zip
    #     asset_name: libzim-wasm_${{ env.VERSION }}.zip
    #     asset_content_type: application/zip
    # - name: Publish zipped ASM artefacts to GitHub release
    #   if: startsWith(env.VERSION, 'v')
    #   uses: actions/upload-release-asset@v1
    #   with:
    #     upload_url: ${{ steps.zip-release.outputs.UPLOAD_URL }} 
    #     asset_path: ./libzim-asm_${{ env.VERSION }}.zip
    #     asset_name: libzim-asm_${{ env.VERSION }}.zip
    #     asset_content_type: application/zip
    # TODO: Publish artefacts to master.download.kiwix.org/release